### ISSUE TITLE
The GMF Tooling project has been archived

### ISSUE THREAD

**Issue by dr6817** [PalladioSimulator/Palladio-Build-UpdateSite#47]
Upon examination of the [nightly.aggr](https://github.com/PalladioSimulator/Palladio-Build-UpdateSite/blob/d7a6c90f3cbf52969d99a8d69c7f9eb599952637/updatesite-aggr/nightly.aggr#L186) file, it was discovered that it contained a [repository location](https://download.eclipse.org/modeling/gmp/gmf-tooling/updates/releases-3.3.1a/) that no longer exists. Since the [GMF Tooling project was archived](https://www.eclipse.org/projects/archives.php) in September 2023, two possible solutions to this problem have been identified. One possible solution is to attempt to remove the dependencies mentioned above. The second possible solution is to host the obsolete update site ourselves.

**Comment by Nicolas-Boltz** [comment]
We have created our own updatesite for the last available and supported version of GMF.
It is available under:
https://updatesite.mdsd.tools/thirdparty-gmf-tooling/updates/releases-3.3.1a/
